export const categories = [
    "Art & Design",
    "Arts & Crafts",
    "Business & Finance",
    "Beauty & Fashion",
    "Community Organizing & Activism",
    "Creative Writing & Literature",
    "Dance & Music",
    "Engineering (Auto, Robotics, etc)",
    "Family, Parenting & Relationships",
    "Film, Photography & Theatre",
    "Food & Culinary Arts",
    "Health, Fitness & Wellness",
    "Home Improvement & Garden",
    "Job Readiness & Professional Development",
    "Languages & Linguistics",
    "Queer & LGBTQQIP2SAA++",
    "Recreation, Games & Sports",
    "Science & Academics",
    "Technology, Coding & Programming",
    "Travel & Adventure"
]
